SELECT
    -- Parent product-level information
    p.ID AS PRODUCT_ID, -- Parent product ID

    -- Variant-level information
    v.VALUE:ADMIN_GRAPHQL_API_ID::STRING AS VARIANT_GRAPHQL_API_ID,
    v.VALUE:BARCODE::STRING AS BARCODE,
    v.VALUE:COMPARE_AT_PRICE::FLOAT AS COMPARE_AT_PRICE,
    TO_TIMESTAMP(v.VALUE:CREATED_AT::INT) AS CREATED_AT, -- Convert UNIX timestamp to readable timestamp
    v.VALUE:FULFILLMENT_SERVICE::STRING AS FULFILLMENT_SERVICE,
    v.VALUE:GRAMS::INT AS GRAMS,
    v.VALUE:ID::STRING AS VARIANT_ID,
    v.VALUE:IMAGE_ID::STRING AS IMAGE_ID,
    v.VALUE:INVENTORY_ITEM_ID::STRING AS INVENTORY_ITEM_ID,
    v.VALUE:INVENTORY_MANAGEMENT::STRING AS INVENTORY_MANAGEMENT,
    v.VALUE:INVENTORY_POLICY::STRING AS INVENTORY_POLICY,
    v.VALUE:INVENTORY_QUANTITY::INT AS INVENTORY_QUANTITY,
    v.VALUE:OLD_INVENTORY_QUANTITY::INT AS OLD_INVENTORY_QUANTITY,
    v.VALUE:OPTION1::STRING AS OPTION_1,
    v.VALUE:OPTION2::STRING AS OPTION_2,
    v.VALUE:OPTION3::STRING AS OPTION_3,
    v.VALUE:POSITION::INT AS POSITION,
    v.VALUE:PRICE::FLOAT AS PRICE,
    v.VALUE:REQUIRES_SHIPPING::BOOLEAN AS REQUIRES_SHIPPING,
    v.VALUE:SKU::STRING AS SKU,
    v.VALUE:TAXABLE::BOOLEAN AS TAXABLE,
    v.VALUE:TAX_CODE::STRING AS TAX_CODE,
    v.VALUE:TITLE::STRING AS VARIANT_TITLE,
    TO_TIMESTAMP(v.VALUE:UPDATED_AT::INT) AS UPDATED_AT, -- Convert UNIX timestamp to readable timestamp
    v.VALUE:WEIGHT::FLOAT AS WEIGHT,
    v.VALUE:WEIGHT_UNIT::STRING AS WEIGHT_UNIT

FROM {{ source('portable_shopify','products')}} p,
     TABLE(FLATTEN(INPUT => p.VARIANTS)) v