SELECT
    -- Parent Order and Refund Information
    o.ID AS ORDER_ID,
    r.VALUE:ID::STRING AS REFUND_ID,

    -- Refund Line Item Information
    rli.VALUE:ID::STRING AS REFUND_LINE_ITEM_ID,
    rli.VALUE:LINE_ITEM:ID::STRING AS LINE_ITEM_ID,
    rli.VALUE:LINE_ITEM:ADMIN_GRAPHQL_API_ID::STRING AS LINE_ITEM_GRAPHQL_API_ID,
    rli.VALUE:LINE_ITEM:NAME::STRING AS LINE_ITEM_NAME,
    rli.VALUE:LINE_ITEM:SKU::STRING AS LINE_ITEM_SKU,
    rli.VALUE:LINE_ITEM:PRICE::FLOAT AS LINE_ITEM_PRICE,
    rli.VALUE:LINE_ITEM:PRICE_SET:PRESENTMENT_MONEY:AMOUNT::FLOAT AS LINE_ITEM_PRESENTMENT_PRICE,
    rli.VALUE:LINE_ITEM:PRICE_SET:PRESENTMENT_MONEY:CURRENCY_CODE::STRING AS LINE_ITEM_PRESENTMENT_CURRENCY,
    rli.VALUE:LINE_ITEM:PRICE_SET:SHOP_MONEY:AMOUNT::FLOAT AS LINE_ITEM_SHOP_PRICE,
    rli.VALUE:LINE_ITEM:PRICE_SET:SHOP_MONEY:CURRENCY_CODE::STRING AS LINE_ITEM_SHOP_CURRENCY,
    rli.VALUE:LINE_ITEM:QUANTITY::INT AS LINE_ITEM_QUANTITY,
    rli.VALUE:LINE_ITEM:REQUIRES_SHIPPING::BOOLEAN AS LINE_ITEM_REQUIRES_SHIPPING,
    rli.VALUE:LINE_ITEM:PRODUCT_ID::STRING AS PRODUCT_ID,
    rli.VALUE:LINE_ITEM:PRODUCT_EXISTS::BOOLEAN AS PRODUCT_EXISTS,
    rli.VALUE:LINE_ITEM:VARIANT_ID::STRING AS VARIANT_ID,
    rli.VALUE:LINE_ITEM:VARIANT_TITLE::STRING AS VARIANT_TITLE,
    rli.VALUE:LINE_ITEM:VENDOR::STRING AS VENDOR,
    rli.VALUE:LOCATION_ID::STRING AS LOCATION_ID,
    rli.VALUE:QUANTITY::INT AS REFUND_QUANTITY,
    rli.VALUE:RESTOCK_TYPE::STRING AS RESTOCK_TYPE,
    rli.VALUE:SUBTOTAL::FLOAT AS REFUND_SUBTOTAL,
    rli.VALUE:SUBTOTAL_SET:PRESENTMENT_MONEY:AMOUNT::FLOAT AS REFUND_PRESENTMENT_SUBTOTAL,
    rli.VALUE:SUBTOTAL_SET:PRESENTMENT_MONEY:CURRENCY_CODE::STRING AS REFUND_PRESENTMENT_SUBTOTAL_CURRENCY,
    rli.VALUE:TOTAL_TAX::FLOAT AS REFUND_TOTAL_TAX,
    rli.VALUE:TOTAL_TAX_SET:PRESENTMENT_MONEY:AMOUNT::FLOAT AS REFUND_PRESENTMENT_TOTAL_TAX,
    rli.VALUE:TOTAL_TAX_SET:PRESENTMENT_MONEY:CURRENCY_CODE::STRING AS REFUND_PRESENTMENT_TOTAL_TAX_CURRENCY

FROM
    {{ source('shopify','orders') }} o,
    TABLE(FLATTEN(INPUT => o.REFUNDS)) r,
    TABLE(FLATTEN(INPUT => r.VALUE:REFUND_LINE_ITEMS)) rli
