SELECT
    -- Parent order-level information
    o.ID AS ORDER_ID,

    -- Refund-level information
    r.VALUE:ID::STRING AS REFUND_ID,

    -- Transaction-level information
    t.VALUE:ADMIN_GRAPHQL_API_ID::STRING AS TRANSACTION_GRAPHQL_API_ID,
    t.VALUE:AMOUNT::FLOAT AS TRANSACTION_AMOUNT,
    t.VALUE:AUTHORIZATION::STRING AS TRANSACTION_AUTHORIZATION,
    TO_TIMESTAMP(t.VALUE:CREATED_AT::INT) AS TRANSACTION_CREATED_AT,
    t.VALUE:CURRENCY::STRING AS TRANSACTION_CURRENCY,
    t.VALUE:ID::STRING AS TRANSACTION_ID,
    t.VALUE:KIND::STRING AS TRANSACTION_KIND,
    t.VALUE:MESSAGE::STRING AS TRANSACTION_MESSAGE,
    t.VALUE:STATUS::STRING AS TRANSACTION_STATUS,
    t.VALUE:PAYMENT_DETAILS:CREDIT_CARD_NUMBER::STRING AS TRANSACTION_CARD_NUMBER,
    t.VALUE:PAYMENT_DETAILS:CREDIT_CARD_COMPANY::STRING AS TRANSACTION_CARD_COMPANY,
    t.VALUE:PAYMENT_DETAILS:PAYMENT_METHOD_NAME::STRING AS TRANSACTION_PAYMENT_METHOD_NAME,

    -- Receipt information
    t.VALUE:RECEIPT:ADDRESS_CITY::STRING AS RECEIPT_ADDRESS_CITY,
    t.VALUE:RECEIPT:ADDRESS_COUNTRY::STRING AS RECEIPT_ADDRESS_COUNTRY,
    t.VALUE:RECEIPT:ADDRESS_COUNTRY_CODE::STRING AS RECEIPT_ADDRESS_COUNTRY_CODE,
    t.VALUE:RECEIPT:ADDRESS_NAME::STRING AS RECEIPT_ADDRESS_NAME,
    t.VALUE:RECEIPT:ADDRESS_STATE::STRING AS RECEIPT_ADDRESS_STATE,
    t.VALUE:RECEIPT:ADDRESS_STREET::STRING AS RECEIPT_ADDRESS_STREET,
    t.VALUE:RECEIPT:ADDRESS_ZIP::STRING AS RECEIPT_ADDRESS_ZIP,
    t.VALUE:RECEIPT:AMOUNT::FLOAT AS RECEIPT_AMOUNT,
    t.VALUE:RECEIPT:AUTHORIZATION_ID::STRING AS RECEIPT_AUTHORIZATION_ID,
    t.VALUE:RECEIPT:BUSINESS::STRING AS RECEIPT_BUSINESS,
    t.VALUE:RECEIPT:CHARGE::STRING AS RECEIPT_CHARGE,
    t.VALUE:RECEIPT:CURRENCY::STRING AS RECEIPT_CURRENCY,
    t.VALUE:RECEIPT:ERROR::STRING AS RECEIPT_ERROR,
    t.VALUE:RECEIPT:MESSAGE::STRING AS RECEIPT_MESSAGE,
    t.VALUE:RECEIPT:METADATA::STRING AS RECEIPT_METADATA,
    t.VALUE:RECEIPT:STATUS::STRING AS RECEIPT_STATUS

FROM {{ source('portable_shopify','orders') }} o,
     TABLE(FLATTEN(INPUT => o.REFUNDS)) r,
     TABLE(FLATTEN(INPUT => r.VALUE:TRANSACTIONS)) t