select 
    -- Order-level information
    o.ID AS ORDER_ID, -- Parent order ID

    l.VALUE:ID::STRING AS LINE_ITEM_ID,

    -- Tax Lines
    t.VALUE:TITLE::STRING AS TAX_TITLE,
    t.VALUE:PRICE::FLOAT AS TAX_PRICE,
    t.VALUE:RATE::FLOAT AS TAX_RATE,
    t.VALUE:PRICE_SET:PRESENTMENT_MONEY:AMOUNT::FLOAT AS TAX_PRESENTMENT_AMOUNT,
    t.VALUE:PRICE_SET:PRESENTMENT_MONEY:CURRENCY_CODE::STRING AS TAX_PRESENTMENT_CURRENCY,
    t.VALUE:PRICE_SET:SHOP_MONEY:AMOUNT::FLOAT AS TAX_SHOP_AMOUNT,
    t.VALUE:PRICE_SET:SHOP_MONEY:CURRENCY_CODE::STRING AS TAX_SHOP_CURRENCY
from {{ source('shopify','orders') }} o,
     TABLE(FLATTEN(INPUT => o.LINE_ITEMS)) l


-- Flatten TAX_LINES (nested array inside LINE_ITEMS)
LEFT JOIN TABLE(FLATTEN(INPUT => l.VALUE:TAX_LINES)) t