SELECT
    -- Parent product-level information
    p.ID AS PRODUCT_ID,                       -- Parent product ID

    -- Variant-level information
    v->>'ADMIN_GRAPHQL_API_ID' AS VARIANT_GRAPHQL_API_ID,
    v->>'BARCODE'               AS BARCODE,
    CAST(v->>'COMPARE_AT_PRICE' AS DOUBLE) AS COMPARE_AT_PRICE,
    TO_TIMESTAMP(CAST(v->>'CREATED_AT' AS BIGINT)) AS CREATED_AT,
    v->>'FULFILLMENT_SERVICE'   AS FULFILLMENT_SERVICE,
    CAST(v->>'GRAMS' AS INTEGER) AS GRAMS,
    v->>'ID'                    AS VARIANT_ID,
    v->>'IMAGE_ID'              AS IMAGE_ID,
    v->>'INVENTORY_ITEM_ID'     AS INVENTORY_ITEM_ID,
    v->>'INVENTORY_MANAGEMENT'  AS INVENTORY_MANAGEMENT,
    v->>'INVENTORY_POLICY'      AS INVENTORY_POLICY,
    CAST(v->>'INVENTORY_QUANTITY' AS INTEGER) AS INVENTORY_QUANTITY,
    CAST(v->>'OLD_INVENTORY_QUANTITY' AS INTEGER) AS OLD_INVENTORY_QUANTITY,
    v->>'OPTION1'               AS OPTION_1,
    v->>'OPTION2'               AS OPTION_2,
    v->>'OPTION3'               AS OPTION_3,
    CAST(v->>'POSITION' AS INTEGER) AS POSITION,
    CAST(v->>'PRICE' AS DOUBLE) AS PRICE,
    CAST(v->>'REQUIRES_SHIPPING' AS BOOLEAN) AS REQUIRES_SHIPPING,
    v->>'SKU'                   AS SKU,
    CAST(v->>'TAXABLE' AS BOOLEAN) AS TAXABLE,
    v->>'TAX_CODE'              AS TAX_CODE,
    v->>'TITLE'                 AS VARIANT_TITLE,
    TO_TIMESTAMP(CAST(v->>'UPDATED_AT' AS BIGINT)) AS UPDATED_AT,
    CAST(v->>'WEIGHT' AS DOUBLE) AS WEIGHT,
    v->>'WEIGHT_UNIT'           AS WEIGHT_UNIT

FROM {{ source('shopify','products')}} p
     , UNNEST(p.VARIANTS) v
