SELECT
    -- Parent order-level information
    o.ID AS ORDER_ID,

    -- Refund-level information
    r.VALUE:ADMIN_GRAPHQL_API_ID::STRING AS REFUND_GRAPHQL_API_ID,
    TO_TIMESTAMP(r.VALUE:CREATED_AT::INT) AS REFUND_CREATED_AT,
    TO_TIMESTAMP(r.VALUE:PROCESSED_AT::INT) AS REFUND_PROCESSED_AT,
    r.VALUE:ID::STRING AS REFUND_ID,
    r.VALUE:NOTE::STRING AS REFUND_NOTE,
    r.VALUE:RESTOCK::BOOLEAN AS REFUND_RESTOCK,
    r.VALUE:TOTAL_DUTIES_SET:PRESENTMENT_MONEY:AMOUNT::FLOAT AS REFUND_TOTAL_DUTIES_PRESENTMENT_AMOUNT,
    r.VALUE:TOTAL_DUTIES_SET:PRESENTMENT_MONEY:CURRENCY_CODE::STRING AS REFUND_TOTAL_DUTIES_PRESENTMENT_CURRENCY,
    r.VALUE:TOTAL_DUTIES_SET:SHOP_MONEY:AMOUNT::FLOAT AS REFUND_TOTAL_DUTIES_SHOP_AMOUNT,
    r.VALUE:TOTAL_DUTIES_SET:SHOP_MONEY:CURRENCY_CODE::STRING AS REFUND_TOTAL_DUTIES_SHOP_CURRENCY,

  
FROM {{ source('shopify','orders') }} o,
     TABLE(FLATTEN(INPUT => o.REFUNDS)) r


