SELECT
    -- Parent order-level information
    o.ID AS ORDER_ID,

    -- Refund-level information
    r->>'ADMIN_GRAPHQL_API_ID' AS REFUND_GRAPHQL_API_ID,
    TO_TIMESTAMP(CAST(r->>'CREATED_AT' AS BIGINT)) AS REFUND_CREATED_AT,
    TO_TIMESTAMP(CAST(r->>'PROCESSED_AT' AS BIGINT)) AS REFUND_PROCESSED_AT,
    r->>'ID' AS REFUND_ID,
    r->>'NOTE' AS REFUND_NOTE,
    r->>'RESTOCK' AS REFUND_RESTOCK,
    r->>'TOTAL_DUTIES_SET'->>'PRESENTMENT_MONEY'->>'AMOUNT' AS REFUND_TOTAL_DUTIES_PRESENTMENT_AMOUNT,
    r->>'TOTAL_DUTIES_SET'->>'PRESENTMENT_MONEY'->>'CURRENCY_CODE' AS REFUND_TOTAL_DUTIES_PRESENTMENT_CURRENCY,
    r->>'TOTAL_DUTIES_SET'->>'SHOP_MONEY'->>'AMOUNT' AS REFUND_TOTAL_DUTIES_SHOP_AMOUNT,
    r->>'TOTAL_DUTIES_SET'->>'SHOP_MONEY'->>'CURRENCY_CODE' AS REFUND_TOTAL_DUTIES_SHOP_CURRENCY,

FROM {{ source('shopify','orders') }} o,
     UNNEST(o.REFUNDS) AS r


