select 
    -- Order-level information
    o.ID AS ORDER_ID, -- Parent order ID

    -- Line-item-level information
    l.VALUE:ID::STRING AS LINE_ITEM_ID,

    -- Discount Allocations
    d.VALUE:AMOUNT::FLOAT AS DISCOUNT_AMOUNT,
    d.VALUE:DISCOUNT_APPLICATION_INDEX::INT AS DISCOUNT_APPLICATION_INDEX,
    d.VALUE:AMOUNT_SET:PRESENTMENT_MONEY:AMOUNT::FLOAT AS DISCOUNT_PRESENTMENT_AMOUNT,
    d.VALUE:AMOUNT_SET:PRESENTMENT_MONEY:CURRENCY_CODE::STRING AS DISCOUNT_PRESENTMENT_CURRENCY,
    d.VALUE:AMOUNT_SET:SHOP_MONEY:AMOUNT::FLOAT AS DISCOUNT_SHOP_AMOUNT,
    d.VALUE:AMOUNT_SET:SHOP_MONEY:CURRENCY_CODE::STRING AS DISCOUNT_SHOP_CURRENCY,

from {{ source('shopify','orders') }} o,
     TABLE(FLATTEN(INPUT => o.LINE_ITEMS)) l

-- Flatten DISCOUNT_ALLOCATIONS (nested array inside LINE_ITEMS)
LEFT JOIN TABLE(FLATTEN(INPUT => l.VALUE:DISCOUNT_ALLOCATIONS)) d

