SELECT
    -- Parent order-level information
    o.ID AS ORDER_ID,

    -- Shipping line-level information
    sl->>'CARRIER_IDENTIFIER' AS CARRIER_IDENTIFIER,
    sl->>'CODE' AS SHIPPING_CODE,
    sl->>'DISCOUNTED_PRICE' AS DISCOUNTED_PRICE,
    sl->>'DISCOUNTED_PRICE_SET'->>'PRESENTMENT_MONEY'->>'AMOUNT' AS DISCOUNTED_PRICE_PRESENTMENT_AMOUNT,
    sl->>'DISCOUNTED_PRICE_SET'->>'PRESENTMENT_MONEY'->>'CURRENCY_CODE' AS DISCOUNTED_PRICE_PRESENTMENT_CURRENCY,
    sl->>'DISCOUNTED_PRICE_SET'->>'SHOP_MONEY'->>'AMOUNT' AS DISCOUNTED_PRICE_SHOP_AMOUNT,
    sl->>'DISCOUNTED_PRICE_SET'->>'SHOP_MONEY'->>'CURRENCY_CODE' AS DISCOUNTED_PRICE_SHOP_CURRENCY,
    sl->>'ID' AS SHIPPING_LINE_ID,
    sl->>'IS_REMOVED' AS IS_REMOVED,
    sl->>'PRICE' AS SHIPPING_PRICE,
    sl->>'PRICE_SET'->>'PRESENTMENT_MONEY'->>'AMOUNT' AS SHIPPING_PRICE_PRESENTMENT_AMOUNT,
    sl->>'PRICE_SET'->>'PRESENTMENT_MONEY'->>'CURRENCY_CODE' AS SHIPPING_PRICE_PRESENTMENT_CURRENCY,
    sl->>'PRICE_SET'->>'SHOP_MONEY'->>'AMOUNT' AS SHIPPING_PRICE_SHOP_AMOUNT,
    sl->>'PRICE_SET'->>'SHOP_MONEY'->>'CURRENCY_CODE' AS SHIPPING_PRICE_SHOP_CURRENCY,
    sl->>'SOURCE' AS SHIPPING_SOURCE,
    sl->>'TITLE' AS SHIPPING_TITLE

FROM {{ source('shopify','orders') }} o,
     UNNEST(o.SHIPPING_LINES) AS sl
