select 
    -- Order-level information
    o.ID AS ORDER_ID, -- Parent order ID

    -- Line-item-level information
    l.VALUE:ADMIN_GRAPHQL_API_ID::STRING AS ADMIN_GRAPHQL_API_ID,
    l.VALUE:CURRENT_QUANTITY::INT AS CURRENT_QUANTITY,
    l.VALUE:FULFILLABLE_QUANTITY::INT AS FULFILLABLE_QUANTITY,
    l.VALUE:FULFILLMENT_SERVICE::STRING AS FULFILLMENT_SERVICE,
    l.VALUE:FULFILLMENT_STATUS::STRING AS FULFILLMENT_STATUS,
    l.VALUE:GIFT_CARD::BOOLEAN AS GIFT_CARD,
    l.VALUE:GRAMS::INT AS GRAMS,
    l.VALUE:ID::STRING AS LINE_ITEM_ID,
    l.VALUE:NAME::STRING AS ITEM_NAME,
    l.VALUE:PRE_TAX_PRICE::FLOAT AS PRE_TAX_PRICE,
    l.VALUE:PRICE::FLOAT AS PRICE,
    l.VALUE:QUANTITY::INT AS ITEM_QUANTITY,
    l.VALUE:REQUIRES_SHIPPING::BOOLEAN AS REQUIRES_SHIPPING,
    l.VALUE:SKU::STRING AS SKU,
    l.VALUE:TAXABLE::BOOLEAN AS TAXABLE,
    l.VALUE:TITLE::STRING AS ITEM_TITLE,
    sum(d.VALUE:AMOUNT::FLOAT) AS TOTAL_DISCOUNT,
    l.VALUE:VARIANT_ID::STRING AS VARIANT_ID,
    l.VALUE:VARIANT_INVENTORY_MANAGEMENT::STRING AS VARIANT_INVENTORY_MANAGEMENT,
    l.VALUE:VARIANT_TITLE::STRING AS VARIANT_TITLE,
    l.VALUE:VENDOR::STRING AS VENDOR,
    l.VALUE:PRODUCT_ID::STRING AS PRODUCT_ID

from {{ source('shopify','orders') }} o,
     TABLE(FLATTEN(INPUT => o.LINE_ITEMS)) l,
     LATERAL FLATTEN(input => l.value:DISCOUNT_ALLOCATIONS, OUTER => TRUE) d
GROUP BY ALL
