select 
    -- Order-level information
    o.ID AS ORDER_ID, -- Parent order ID

    -- Line-item-level information
    l->>'ADMIN_GRAPHQL_API_ID' AS ADMIN_GRAPHQL_API_ID,
    l->>'CURRENT_QUANTITY' AS CURRENT_QUANTITY,
    l->>'FULFILLABLE_QUANTITY' AS FULFILLABLE_QUANTITY,
    l->>'FULFILLMENT_SERVICE' AS FULFILLMENT_SERVICE,
    l->>'FULFILLMENT_STATUS' AS FULFILLMENT_STATUS,
    l->>'GIFT_CARD' AS GIFT_CARD,
    l->>'GRAMS' AS GRAMS,
    l->>'ID' AS LINE_ITEM_ID,
    l->>'NAME' AS ITEM_NAME,
    l->>'PRE_TAX_PRICE' AS PRE_TAX_PRICE,
    l->>'PRICE' AS PRICE,
    l->>'QUANTITY' AS ITEM_QUANTITY,
    l->>'REQUIRES_SHIPPING' AS REQUIRES_SHIPPING,
    l->>'SKU' AS SKU,
    l->>'TAXABLE' AS TAXABLE,
    l->>'TITLE' AS ITEM_TITLE,
    0 AS TOTAL_DISCOUNT,
    l->>'VARIANT_ID' AS VARIANT_ID,
    l->>'VARIANT_INVENTORY_MANAGEMENT' AS VARIANT_INVENTORY_MANAGEMENT,
    l->>'VARIANT_TITLE' AS VARIANT_TITLE,
    l->>'VENDOR' AS VENDOR,
    l->>'PRODUCT_ID' AS PRODUCT_ID

from {{ source('shopify','orders') }} o,
     unnest(o.LINE_ITEMS) l