SELECT
    -- Parent Customer Information
    c.ID AS CUSTOMER_ID,
    CREATED_AT,
    -- Address Fields
    addr.VALUE:ID::STRING AS ADDRESS_ID,
    addr.VALUE:ADDRESS1::STRING AS ADDRESS_1,
    addr.VALUE:ADDRESS2::STRING AS ADDRESS_2,
    addr.VALUE:CITY::STRING AS CITY,
    addr.VALUE:COMPANY::STRING AS COMPANY,
    addr.VALUE:COUNTRY::STRING AS COUNTRY,
    addr.VALUE:COUNTRY_CODE::STRING AS COUNTRY_CODE,
    addr.VALUE:COUNTRY_NAME::STRING AS COUNTRY_NAME,
    addr.VALUE:CUSTOMER_ID::STRING AS CUSTOMER_REF_ID,
    addr.VALUE:DEFAULT::BOOLEAN AS IS_DEFAULT,
    addr.VALUE:FIRST_NAME::STRING AS FIRST_NAME,
    addr.VALUE:LAST_NAME::STRING AS LAST_NAME,
    addr.VALUE:NAME::STRING AS FULL_NAME,
    addr.VALUE:PHONE::STRING AS PHONE,
    addr.VALUE:PROVINCE::STRING AS PROVINCE,
    addr.VALUE:PROVINCE_CODE::STRING AS PROVINCE_CODE,
    addr.VALUE:ZIP::STRING AS ZIP
FROM
    {{ source('shopify','customers') }} c,
    TABLE(FLATTEN(INPUT => c.ADDRESSES)) addr -- Flatten the addresses array