SELECT
    -- Parent order-level information
    o.ID AS ORDER_ID,

    -- Refund-level information
    r.VALUE:ID::STRING AS REFUND_ID,

    -- Order Adjustments (nested array inside REFUNDS)
    oa.VALUE:ID::STRING AS ORDER_ADJUSTMENT_ID,
    oa.VALUE:AMOUNT::FLOAT AS ORDER_ADJUSTMENT_AMOUNT,
    oa.VALUE:KIND::STRING AS ORDER_ADJUSTMENT_KIND,
    oa.VALUE:REASON::STRING AS ORDER_ADJUSTMENT_REASON,
    oa.VALUE:TAX_AMOUNT::FLOAT AS ORDER_ADJUSTMENT_TAX_AMOUNT,
    oa.VALUE:TAX_AMOUNT_SET:PRESENTMENT_MONEY:AMOUNT::FLOAT AS ORDER_ADJUSTMENT_TAX_PRESENTMENT_AMOUNT,
    oa.VALUE:TAX_AMOUNT_SET:PRESENTMENT_MONEY.CURRENCY_CODE::STRING AS ORDER_ADJUSTMENT_TAX_PRESENTMENT_CURRENCY,
    oa.VALUE:TAX_AMOUNT_SET:SHOP_MONEY:AMOUNT::FLOAT AS ORDER_ADJUSTMENT_TAX_SHOP_AMOUNT,
    oa.VALUE:TAX_AMOUNT_SET:SHOP_MONEY:CURRENCY_CODE::STRING AS ORDER_ADJUSTMENT_TAX_SHOP_CURRENCY,

  
FROM {{ source('portable_shopify','orders') }} o,
     TABLE(FLATTEN(INPUT => o.REFUNDS)) r

-- Flatten ORDER_ADJUSTMENTS (nested array inside REFUNDS)
LEFT JOIN TABLE(FLATTEN(INPUT => r.VALUE:ORDER_ADJUSTMENTS)) oa

