SELECT
    -- Parent order-level information
    o.ID AS ORDER_ID,

    -- Shipping line-level information
    sl.VALUE:CARRIER_IDENTIFIER::STRING AS CARRIER_IDENTIFIER,
    sl.VALUE:CODE::STRING AS SHIPPING_CODE,
    sl.VALUE:DISCOUNTED_PRICE::FLOAT AS DISCOUNTED_PRICE,
    sl.VALUE:DISCOUNTED_PRICE_SET:PRESENTMENT_MONEY:AMOUNT::FLOAT AS DISCOUNTED_PRICE_PRESENTMENT_AMOUNT,
    sl.VALUE:DISCOUNTED_PRICE_SET:PRESENTMENT_MONEY:CURRENCY_CODE::STRING AS DISCOUNTED_PRICE_PRESENTMENT_CURRENCY,
    sl.VALUE:DISCOUNTED_PRICE_SET:SHOP_MONEY:AMOUNT::FLOAT AS DISCOUNTED_PRICE_SHOP_AMOUNT,
    sl.VALUE:DISCOUNTED_PRICE_SET:SHOP_MONEY:CURRENCY_CODE::STRING AS DISCOUNTED_PRICE_SHOP_CURRENCY,
    sl.VALUE:ID::STRING AS SHIPPING_LINE_ID,
    sl.VALUE:IS_REMOVED::BOOLEAN AS IS_REMOVED,
    sl.VALUE:PRICE::FLOAT AS SHIPPING_PRICE,
    sl.VALUE:PRICE_SET:PRESENTMENT_MONEY:AMOUNT::FLOAT AS SHIPPING_PRICE_PRESENTMENT_AMOUNT,
    sl.VALUE:PRICE_SET:PRESENTMENT_MONEY:CURRENCY_CODE::STRING AS SHIPPING_PRICE_PRESENTMENT_CURRENCY,
    sl.VALUE:PRICE_SET:SHOP_MONEY:AMOUNT::FLOAT AS SHIPPING_PRICE_SHOP_AMOUNT,
    sl.VALUE:PRICE_SET:SHOP_MONEY:CURRENCY_CODE::STRING AS SHIPPING_PRICE_SHOP_CURRENCY,
    sl.VALUE:SOURCE::STRING AS SHIPPING_SOURCE,
    sl.VALUE:TITLE::STRING AS SHIPPING_TITLE

FROM {{ source('shopify','orders') }} o,
     TABLE(FLATTEN(INPUT => o.SHIPPING_LINES)) sl