with source as (
    select * from shopify.main.orders
),
renamed as (
    select
        CAST("ADMIN_GRAPHQL_API_ID" AS VARCHAR) as admin_graphql_api_id,
        CAST("APP_ID" AS VARCHAR) as app_id,
        "BROWSER_IP",
        "BUYER_ACCEPTS_MARKETING",
        "CANCEL_REASON",
        "CANCELLED_AT",
        "CART_TOKEN",
        CAST("CHECKOUT_ID" AS VARCHAR) as checkout_id,
        "CHECKOUT_TOKEN",
        "CLOSED_AT",
        CAST("CONFIRMATION_NUMBER" AS VARCHAR) as confirmation_number,
        "CONFIRMED",
        "CONTACT_EMAIL",
        "CREATED_AT",
        "CURRENCY",
        CAST("CURRENT_SUBTOTAL_PRICE" AS DOUBLE) as current_subtotal_price,
        "CURRENT_TOTAL_ADDITIONAL_FEES_SET",
        CAST("CURRENT_TOTAL_DISCOUNTS" AS DOUBLE) as current_total_discounts,
        "CURRENT_TOTAL_DUTIES_SET",
        CAST("CURRENT_TOTAL_PRICE" AS DOUBLE) as current_total_price,
        CAST("CURRENT_TOTAL_TAX" AS DOUBLE) as current_total_tax,
        "CUSTOMER_LOCALE",
        "DUTIES_INCLUDED",
        "EMAIL",
        "ESTIMATED_TAXES",
        "FINANCIAL_STATUS",
        "FULFILLMENT_STATUS",
        CAST("ID" AS VARCHAR) as order_id,
        "LANDING_SITE",
        "LANDING_SITE_REF",
        CAST("LOCATION_ID" AS VARCHAR) as location_id,
        "MERCHANT_BUSINESS_ENTITY_ID",
        "NAME",
        "NOTE",
        CAST("NUMBER" AS VARCHAR) as number,
        CAST("ORDER_NUMBER" AS VARCHAR) as order_number,
        "ORDER_STATUS_URL",
        "ORIGINAL_TOTAL_DUTIES_SET",
        "PAYMENT_GATEWAY_NAMES",
        "PAYMENT_TERMS",
        "PHONE",
        "PRESENTMENT_CURRENCY",
        "PROCESSED_AT",
        "REFERENCE",
        "REFERRING_SITE",
        "REFUNDS",
        "SOURCE_IDENTIFIER",
        "SOURCE_NAME",
        CAST("SUBTOTAL_PRICE" AS DOUBLE) as subtotal_price,
        "TAGS",
        "TAX_EXEMPT",
        "TAXES_INCLUDED",
        "TEST",
        "TOKEN",
        CAST("TOTAL_DISCOUNTS" AS DOUBLE) as total_discounts,
        CAST("TOTAL_LINE_ITEMS_PRICE" AS DOUBLE) as total_line_items_price,
        CAST("TOTAL_OUTSTANDING" AS DOUBLE) as total_outstanding,
        CAST("TOTAL_PRICE" AS DOUBLE) as total_price,
        CAST("TOTAL_TAX" AS DOUBLE) as total_tax,
        CAST("TOTAL_TIP_RECEIVED" AS DOUBLE) as total_tip_received,
        CAST("TOTAL_WEIGHT" AS DOUBLE) as total_weight,
        "UPDATED_AT",
        CAST("USER_ID" AS VARCHAR) as user_id,

        -- Billing Address Fields
        CAST(json_extract("BILLING_ADDRESS", '$.ADDRESS1') AS VARCHAR) AS billing_address1,
        CAST(json_extract("BILLING_ADDRESS", '$.ADDRESS2') AS VARCHAR) AS billing_address2,
        CAST(json_extract("BILLING_ADDRESS", '$.CITY') AS VARCHAR) AS billing_city,
        CAST(json_extract("BILLING_ADDRESS", '$.COMPANY') AS VARCHAR) AS billing_company,
        CAST(json_extract("BILLING_ADDRESS", '$.COUNTRY') AS VARCHAR) AS billing_country,
        CAST(json_extract("BILLING_ADDRESS", '$.COUNTRY_CODE') AS VARCHAR) AS billing_country_code,
        CAST(json_extract("BILLING_ADDRESS", '$.FIRST_NAME') AS VARCHAR) AS billing_first_name,
        CAST(json_extract("BILLING_ADDRESS", '$.LAST_NAME') AS VARCHAR) AS billing_last_name,
        CAST(json_extract("BILLING_ADDRESS", '$.LATITUDE') AS DOUBLE) AS billing_latitude,
        CAST(json_extract("BILLING_ADDRESS", '$.LONGITUDE') AS DOUBLE) AS billing_longitude,
        CAST(json_extract("BILLING_ADDRESS", '$.NAME') AS VARCHAR) AS billing_name,
        CAST(json_extract("BILLING_ADDRESS", '$.PHONE') AS VARCHAR) AS billing_phone,
        CAST(json_extract("BILLING_ADDRESS", '$.PROVINCE') AS VARCHAR) AS billing_province,
        CAST(json_extract("BILLING_ADDRESS", '$.PROVINCE_CODE') AS VARCHAR) AS billing_province_code,
        CAST(json_extract("BILLING_ADDRESS", '$.ZIP') AS VARCHAR) AS billing_zip,

        -- Shipping Address Fields
        CAST(json_extract("SHIPPING_ADDRESS", '$.ADDRESS1') AS VARCHAR) AS shipping_address1,
        CAST(json_extract("SHIPPING_ADDRESS", '$.ADDRESS2') AS VARCHAR) AS shipping_address2,
        CAST(json_extract("SHIPPING_ADDRESS", '$.CITY') AS VARCHAR) AS shipping_address_city,
        CAST(json_extract("SHIPPING_ADDRESS", '$.COMPANY') AS VARCHAR) AS shipping_address_company,
        CAST(json_extract("SHIPPING_ADDRESS", '$.COUNTRY') AS VARCHAR) AS shipping_address_country,
        CAST(json_extract("SHIPPING_ADDRESS", '$.COUNTRY_CODE') AS VARCHAR) AS shipping_address_country_code,
        CAST(json_extract("SHIPPING_ADDRESS", '$.FIRST_NAME') AS VARCHAR) AS shipping_address_first_name,
        CAST(json_extract("SHIPPING_ADDRESS", '$.LAST_NAME') AS VARCHAR) AS shipping_address_last_name,
        CAST(json_extract("SHIPPING_ADDRESS", '$.LATITUDE') AS DOUBLE) AS shipping_address_latitude,
        CAST(json_extract("SHIPPING_ADDRESS", '$.LONGITUDE') AS DOUBLE) AS shipping_address_longitude,
        CAST(json_extract("SHIPPING_ADDRESS", '$.NAME') AS VARCHAR) AS shipping_address_name,
        CAST(json_extract("SHIPPING_ADDRESS", '$.PHONE') AS VARCHAR) AS shipping_address_phone,
        CAST(json_extract("SHIPPING_ADDRESS", '$.PROVINCE') AS VARCHAR) AS shipping_address_province,
        CAST(json_extract("SHIPPING_ADDRESS", '$.PROVINCE_CODE') AS VARCHAR) AS shipping_address_province_code,
        CAST(json_extract("SHIPPING_ADDRESS", '$.ZIP') AS VARCHAR) AS shipping_address_zip,

        -- Customer Fields
        CAST(json_extract("CUSTOMER", '$.ADMIN_GRAPHQL_API_ID') AS VARCHAR) AS customer_graphql_api_id,
        TO_TIMESTAMP(CAST(json_extract("CUSTOMER", '$.CREATED_AT') AS BIGINT)) AS customer_created_at,
        CAST(json_extract("CUSTOMER", '$.CURRENCY') AS VARCHAR) AS customer_currency,
        CAST(json_extract("CUSTOMER", '$.EMAIL') AS VARCHAR) AS customer_email,
        CAST(json_extract("CUSTOMER", '$.FIRST_NAME') AS VARCHAR) AS customer_first_name,
        CAST(json_extract("CUSTOMER", '$.LAST_NAME') AS VARCHAR) AS customer_last_name,
        CAST(json_extract("CUSTOMER", '$.ID') AS VARCHAR) AS customer_id,
        CAST(json_extract("CUSTOMER", '$.PHONE') AS VARCHAR) AS customer_phone,
        CAST(json_extract("CUSTOMER", '$.STATE') AS VARCHAR) AS customer_state,
        CAST(json_extract("CUSTOMER", '$.TAGS') AS VARCHAR) AS customer_tags,
        CAST(json_extract("CUSTOMER", '$.TAX_EXEMPT') AS BOOLEAN) AS customer_tax_exempt,
        TO_TIMESTAMP(CAST(json_extract("CUSTOMER", '$.UPDATED_AT') AS BIGINT)) AS customer_updated_at,
        CAST(json_extract("CUSTOMER", '$.VERIFIED_EMAIL') AS BOOLEAN) AS customer_verified_email,

        -- Email Marketing Consent
        TO_TIMESTAMP(CAST(json_extract("CUSTOMER", '$.EMAIL_MARKETING_CONSENT.CONSENT_UPDATED_AT') AS BIGINT)) AS email_consent_updated_at,
        CAST(json_extract("CUSTOMER", '$.EMAIL_MARKETING_CONSENT.OPT_IN_LEVEL') AS VARCHAR) AS email_opt_in_level,
        CAST(json_extract("CUSTOMER", '$.EMAIL_MARKETING_CONSENT.STATE') AS VARCHAR) AS email_marketing_state,

        -- SMS Marketing Consent
        CAST(json_extract("CUSTOMER", '$.SMS_MARKETING_CONSENT.CONSENT_COLLECTED_FROM') AS VARCHAR) AS sms_consent_collected_from,
        TO_TIMESTAMP(CAST(json_extract("CUSTOMER", '$.SMS_MARKETING_CONSENT.CONSENT_UPDATED_AT') AS BIGINT)) AS sms_consent_updated_at,
        CAST(json_extract("CUSTOMER", '$.SMS_MARKETING_CONSENT.OPT_IN_LEVEL') AS VARCHAR) AS sms_opt_in_level,
        CAST(json_extract("CUSTOMER", '$.SMS_MARKETING_CONSENT.STATE') AS VARCHAR) AS sms_marketing_state,

        -- Default Address Fields
        CAST(json_extract("CUSTOMER", '$.DEFAULT_ADDRESS.ADDRESS1') AS VARCHAR) AS default_address1,
        CAST(json_extract("CUSTOMER", '$.DEFAULT_ADDRESS.ADDRESS2') AS VARCHAR) AS default_address2,
        CAST(json_extract("CUSTOMER", '$.DEFAULT_ADDRESS.CITY') AS VARCHAR) AS default_city,
        CAST(json_extract("CUSTOMER", '$.DEFAULT_ADDRESS.COUNTRY') AS VARCHAR) AS default_country,
        CAST(json_extract("CUSTOMER", '$.DEFAULT_ADDRESS.COUNTRY_CODE') AS VARCHAR) AS default_country_code,
        CAST(json_extract("CUSTOMER", '$.DEFAULT_ADDRESS.COUNTRY_NAME') AS VARCHAR) AS default_country_name,
        CAST(json_extract("CUSTOMER", '$.DEFAULT_ADDRESS.ZIP') AS VARCHAR) AS default_zip,
        CAST(json_extract("CUSTOMER", '$.DEFAULT_ADDRESS.PROVINCE') AS VARCHAR) AS default_province,
        CAST(json_extract("CUSTOMER", '$.DEFAULT_ADDRESS.PROVINCE_CODE') AS VARCHAR) AS default_province_code,
        CAST(json_extract("CUSTOMER", '$.DEFAULT_ADDRESS.NAME') AS VARCHAR) AS default_name,
        CAST(json_extract("CUSTOMER", '$.DEFAULT_ADDRESS.PHONE') AS VARCHAR) AS default_phone
    from source
)
select * from renamed