with source as (
        select * from {{ source('portable_shopify', 'orders') }}
  ),
  renamed as (
      select
        {{ adapter.quote("_PORTABLE_EXTRACTED") }},
        {{ adapter.quote("ADMIN_GRAPHQL_API_ID") }}::varchar as admin_graphql_api_id,
        {{ adapter.quote("APP_ID") }}::varchar as app_id,
        -- {{ adapter.quote("BILLING_ADDRESS") }},
        {{ adapter.quote("BROWSER_IP") }},
        {{ adapter.quote("BUYER_ACCEPTS_MARKETING") }},
        {{ adapter.quote("CANCEL_REASON") }},
        {{ adapter.quote("CANCELLED_AT") }},
        {{ adapter.quote("CART_TOKEN") }},
        {{ adapter.quote("CHECKOUT_ID") }}::varchar as checkout_id,
        {{ adapter.quote("CHECKOUT_TOKEN") }},
        -- {{ adapter.quote("CLIENT_DETAILS") }},
        {{ adapter.quote("CLOSED_AT") }},
        {{ adapter.quote("CONFIRMATION_NUMBER") }}::varchar as confirmation_number,
        {{ adapter.quote("CONFIRMED") }},
        {{ adapter.quote("CONTACT_EMAIL") }},
        {{ adapter.quote("CREATED_AT") }},
        {{ adapter.quote("CURRENCY") }},
        {{ adapter.quote("CURRENT_SUBTOTAL_PRICE") }}::float as current_subtotal_price,
        -- {{ adapter.quote("CURRENT_SUBTOTAL_PRICE_SET") }},
        {{ adapter.quote("CURRENT_TOTAL_ADDITIONAL_FEES_SET") }},
        {{ adapter.quote("CURRENT_TOTAL_DISCOUNTS") }}::float as current_total_discounts,
        -- {{ adapter.quote("CURRENT_TOTAL_DISCOUNTS_SET") }},
        {{ adapter.quote("CURRENT_TOTAL_DUTIES_SET") }},
        {{ adapter.quote("CURRENT_TOTAL_PRICE") }}::float as current_total_price,
        -- {{ adapter.quote("CURRENT_TOTAL_PRICE_SET") }},
        {{ adapter.quote("CURRENT_TOTAL_TAX") }}::float as current_total_tax,
        -- {{ adapter.quote("CURRENT_TOTAL_TAX_SET") }},
        -- {{ adapter.quote("CUSTOMER") }},
        {{ adapter.quote("CUSTOMER_LOCALE") }},
        -- {{ adapter.quote("DISCOUNT_APPLICATIONS") }},
        -- {{ adapter.quote("DISCOUNT_CODES") }},
        {{ adapter.quote("DUTIES_INCLUDED") }},
        {{ adapter.quote("EMAIL") }},
        {{ adapter.quote("ESTIMATED_TAXES") }},
        {{ adapter.quote("FINANCIAL_STATUS") }},
        {{ adapter.quote("FULFILLMENT_STATUS") }},
        -- {{ adapter.quote("FULFILLMENTS") }},
        {{ adapter.quote("ID") }}::varchar as order_id,
        {{ adapter.quote("LANDING_SITE") }},
        {{ adapter.quote("LANDING_SITE_REF") }},
        -- {{ adapter.quote("LINE_ITEMS") }},
        {{ adapter.quote("LOCATION_ID") }}::varchar as location_id,
        {{ adapter.quote("MERCHANT_BUSINESS_ENTITY_ID") }},
        {{ adapter.quote("NAME") }},
        {{ adapter.quote("NOTE") }},
        -- {{ adapter.quote("NOTE_ATTRIBUTES") }},
        {{ adapter.quote("NUMBER") }}::varchar as number,
        {{ adapter.quote("ORDER_NUMBER") }}::varchar as order_number,
        {{ adapter.quote("ORDER_STATUS_URL") }},
        {{ adapter.quote("ORIGINAL_TOTAL_DUTIES_SET") }},
        {{ adapter.quote("PAYMENT_GATEWAY_NAMES") }},
        {{ adapter.quote("PAYMENT_TERMS") }},
        {{ adapter.quote("PHONE") }},
        {{ adapter.quote("PRESENTMENT_CURRENCY") }},
        {{ adapter.quote("PROCESSED_AT") }},
        {{ adapter.quote("REFERENCE") }},
        {{ adapter.quote("REFERRING_SITE") }},
        {{ adapter.quote("REFUNDS") }},
        -- {{ adapter.quote("SHIPPING_ADDRESS") }},
        -- {{ adapter.quote("SHIPPING_LINES") }},
        {{ adapter.quote("SOURCE_IDENTIFIER") }},
        {{ adapter.quote("SOURCE_NAME") }},
        {{ adapter.quote("SUBTOTAL_PRICE") }}::float as subtotal_price,
        -- {{ adapter.quote("SUBTOTAL_PRICE_SET") }},
        {{ adapter.quote("TAGS") }},
        {{ adapter.quote("TAX_EXEMPT") }},
        -- {{ adapter.quote("TAX_LINES") }},
        {{ adapter.quote("TAXES_INCLUDED") }},
        {{ adapter.quote("TEST") }},
        {{ adapter.quote("TOKEN") }},
        -- {{ adapter.quote("TOTAL_CASH_ROUNDING_PAYMENT_ADJUSTMENT_SET") }},
        -- {{ adapter.quote("TOTAL_CASH_ROUNDING_REFUND_ADJUSTMENT_SET") }},
        {{ adapter.quote("TOTAL_DISCOUNTS") }}::float as total_discounts,
        -- {{ adapter.quote("TOTAL_DISCOUNTS_SET") }},
        {{ adapter.quote("TOTAL_LINE_ITEMS_PRICE") }}::float as total_line_items_price,
        -- {{ adapter.quote("TOTAL_LINE_ITEMS_PRICE_SET") }},
        {{ adapter.quote("TOTAL_OUTSTANDING") }}::float as total_outstanding,
        {{ adapter.quote("TOTAL_PRICE") }}::float as total_price,
        -- {{ adapter.quote("TOTAL_PRICE_SET") }},
        -- {{ adapter.quote("TOTAL_SHIPPING_PRICE_SET") }},
        {{ adapter.quote("TOTAL_TAX") }}::float as total_tax,
        -- {{ adapter.quote("TOTAL_TAX_SET") }},
        {{ adapter.quote("TOTAL_TIP_RECEIVED") }}::float as total_tip_received,
        {{ adapter.quote("TOTAL_WEIGHT") }}::float as total_weight  ,
        {{ adapter.quote("UPDATED_AT") }},
        {{ adapter.quote("USER_ID") }}::varchar as user_id,

        -- Billing Address Fields
        BILLING_ADDRESS:ADDRESS1::STRING AS BILLING_ADDRESS1,
        BILLING_ADDRESS:ADDRESS2::STRING AS BILLING_ADDRESS2,
        BILLING_ADDRESS:CITY::STRING AS BILLING_CITY,
        BILLING_ADDRESS:COMPANY::STRING AS BILLING_COMPANY,
        BILLING_ADDRESS:COUNTRY::STRING AS BILLING_COUNTRY,
        BILLING_ADDRESS:COUNTRY_CODE::STRING AS BILLING_COUNTRY_CODE,
        BILLING_ADDRESS:FIRST_NAME::STRING AS BILLING_FIRST_NAME,
        BILLING_ADDRESS:LAST_NAME::STRING AS BILLING_LAST_NAME,
        BILLING_ADDRESS:LATITUDE::FLOAT AS BILLING_LATITUDE,
        BILLING_ADDRESS:LONGITUDE::FLOAT AS BILLING_LONGITUDE,
        BILLING_ADDRESS:NAME::STRING AS BILLING_NAME,
        BILLING_ADDRESS:PHONE::STRING AS BILLING_PHONE,
        BILLING_ADDRESS:PROVINCE::STRING AS BILLING_PROVINCE,
        BILLING_ADDRESS:PROVINCE_CODE::STRING AS BILLING_PROVINCE_CODE,
        BILLING_ADDRESS:ZIP::STRING AS BILLING_ZIP,

        -- Shipping Address Fields
        SHIPPING_ADDRESS:ADDRESS1::STRING AS SHIPPING_ADDRESS1,
        SHIPPING_ADDRESS:ADDRESS2::STRING AS SHIPPING_ADDRESS2,
        SHIPPING_ADDRESS:CITY::STRING AS SHIPPING_ADDRESS_CITY,
        SHIPPING_ADDRESS:COMPANY::STRING AS SHIPPING_ADDRESS_COMPANY,
        SHIPPING_ADDRESS:COUNTRY::STRING AS SHIPPING_ADDRESS_COUNTRY,
        SHIPPING_ADDRESS:COUNTRY_CODE::STRING AS SHIPPING_ADDRESS_COUNTRY_CODE,
        SHIPPING_ADDRESS:FIRST_NAME::STRING AS SHIPPING_ADDRESS_FIRST_NAME,
        SHIPPING_ADDRESS:LAST_NAME::STRING AS SHIPPING_ADDRESS_LAST_NAME,
        SHIPPING_ADDRESS:LATITUDE::FLOAT AS SHIPPING_ADDRESS_LATITUDE,
        SHIPPING_ADDRESS:LONGITUDE::FLOAT AS SHIPPING_ADDRESS_LONGITUDE,
        SHIPPING_ADDRESS:NAME::STRING AS SHIPPING_ADDRESS_NAME,
        SHIPPING_ADDRESS:PHONE::STRING AS SHIPPING_ADDRESS_PHONE,
        SHIPPING_ADDRESS:PROVINCE::STRING AS SHIPPING_ADDRESS_PROVINCE,
        SHIPPING_ADDRESS:PROVINCE_CODE::STRING AS SHIPPING_ADDRESS_PROVINCE_CODE,
        SHIPPING_ADDRESS:ZIP::STRING AS SHIPPING_ADDRESS_ZIP,

        -- Customer Fields
        CUSTOMER:ADMIN_GRAPHQL_API_ID::STRING AS CUSTOMER_GRAPHQL_API_ID,
        TO_TIMESTAMP(CUSTOMER:CREATED_AT::INT) AS CUSTOMER_CREATED_AT,
        CUSTOMER:CURRENCY::STRING AS CUSTOMER_CURRENCY,
        CUSTOMER:EMAIL::STRING AS CUSTOMER_EMAIL,
        CUSTOMER:FIRST_NAME::STRING AS CUSTOMER_FIRST_NAME,
        CUSTOMER:LAST_NAME::STRING AS CUSTOMER_LAST_NAME,
        CUSTOMER:ID::STRING AS CUSTOMER_ID,
        CUSTOMER:PHONE::STRING AS CUSTOMER_PHONE,
        CUSTOMER:STATE::STRING AS CUSTOMER_STATE,
        CUSTOMER:TAGS::STRING AS CUSTOMER_TAGS,
        CUSTOMER:TAX_EXEMPT::BOOLEAN AS CUSTOMER_TAX_EXEMPT,
        TO_TIMESTAMP(CUSTOMER:UPDATED_AT::INT) AS CUSTOMER_UPDATED_AT,
        CUSTOMER:VERIFIED_EMAIL::BOOLEAN AS CUSTOMER_VERIFIED_EMAIL,

        -- Email Marketing Consent
        TO_TIMESTAMP(CUSTOMER:EMAIL_MARKETING_CONSENT:CONSENT_UPDATED_AT::INT) AS EMAIL_CONSENT_UPDATED_AT,
        CUSTOMER:EMAIL_MARKETING_CONSENT:OPT_IN_LEVEL::STRING AS EMAIL_OPT_IN_LEVEL,
        CUSTOMER:EMAIL_MARKETING_CONSENT:STATE::STRING AS EMAIL_MARKETING_STATE,

        -- SMS Marketing Consent
        CUSTOMER:SMS_MARKETING_CONSENT:CONSENT_COLLECTED_FROM::STRING AS SMS_CONSENT_COLLECTED_FROM,
        TO_TIMESTAMP(CUSTOMER:SMS_MARKETING_CONSENT:CONSENT_UPDATED_AT::INT) AS SMS_CONSENT_UPDATED_AT,
        CUSTOMER:SMS_MARKETING_CONSENT:OPT_IN_LEVEL::STRING AS SMS_OPT_IN_LEVEL,
        CUSTOMER:SMS_MARKETING_CONSENT:STATE::STRING AS SMS_MARKETING_STATE,

        -- Default Address Fields
        CUSTOMER:DEFAULT_ADDRESS:ADDRESS1::STRING AS DEFAULT_ADDRESS1,
        CUSTOMER:DEFAULT_ADDRESS:ADDRESS2::STRING AS DEFAULT_ADDRESS2,
        CUSTOMER:DEFAULT_ADDRESS:CITY::STRING AS DEFAULT_CITY,
        CUSTOMER:DEFAULT_ADDRESS:COUNTRY::STRING AS DEFAULT_COUNTRY,
        CUSTOMER:DEFAULT_ADDRESS:COUNTRY_CODE::STRING AS DEFAULT_COUNTRY_CODE,
        CUSTOMER:DEFAULT_ADDRESS:COUNTRY_NAME::STRING AS DEFAULT_COUNTRY_NAME,
        CUSTOMER:DEFAULT_ADDRESS:ZIP::STRING AS DEFAULT_ZIP,
        CUSTOMER:DEFAULT_ADDRESS:PROVINCE::STRING AS DEFAULT_PROVINCE,
        CUSTOMER:DEFAULT_ADDRESS:PROVINCE_CODE::STRING AS DEFAULT_PROVINCE_CODE,
        CUSTOMER:DEFAULT_ADDRESS:NAME::STRING AS DEFAULT_NAME,
        CUSTOMER:DEFAULT_ADDRESS:PHONE::STRING AS DEFAULT_PHONE
      from source
  )
  select * from renamed