SELECT
    ID AS SURVEY_ID,
    CUSTOMER_ID::VARCHAR AS CUSTOMER_ID,
    TICKET_ID::VARCHAR AS TICKET_ID,
    SCORE::INTEGER AS SCORE,
    BODY_TEXT::VARCHAR AS BODY_TEXT,
    CREATED_DATETIME,
    SCORED_DATETIME,
    SENT_DATETIME ,
    SHOULD_SEND_DATETIME,
    URI
FROM {{ source('portable_gorgias', 'satisfaction_surveys') }}
