    SELECT 
        ID::VARCHAR AS TAG_ID,
        _FIVETRAN_DELETED::BOOLEAN AS _FIVETRAN_DELETED,
        _FIVETRAN_SYNCED::TIMESTAMP AS _FIVETRAN_SYNCED,
        DECORATION_COLOR::VARCHAR AS DECORATION_COLOR,
        USAGE::VARCHAR AS USAGE,
        NAME::VARCHAR AS NAME,
        CREATED_DATETIME::TIMESTAMP AS CREATED_DATETIME
FROM {{ source('portable_gorgias', 'tags') }}