version: 2

sources:
  - name: shopify              # you can pick any logical name
    schema: main               # the schema inside DuckDB (default is "main")
    tables:
      - name: customers
      - name: orders
      - name: products
