version: 2
sources:

  - name: shopify_raw
    database: raw    
    schema: shopify
    tables:
      - name: adjustment_order_transaction
      - name: balance_transaction
      - name: customer
      - name: customer_address
      - name: customer_segment
      - name: customer_tag
      - name: discount_allocation
      - name: discount_application
      - name: discount_code
      - name: fulfillment
      - name: fulfillment_event
      - name: fulfillment_order
      - name: fulfillment_order_line_item
      - name: inventory_item
      - name: inventory_level
      - name: order
      - name: order_discount_code
      - name: order_line
      - name: order_line_refund
      - name: order_shipping_line
      - name: order_shipping_tax_line
      - name: order_tag
      - name: order_note_attribute
      - name: product
      - name: product_image
      - name: product_option
      - name: product_tag
      - name: product_variant
      - name: refund
      - name: tax_line
      - name: transaction
      - name: user
      - name: order_adjustment
    
  - name: amazon_raw
    database: raw    
    schema: amazon_selling_partner
    tables:
      - name: ORDER_ITEM
      - name: ORDERS
      - name: FINANCIAL_COUPON_PAYMENT_EVENT
      - name: financial_seller_deal_payment_event
      - name: financial_service_fee_event
      - name: financial_shipment_event
      - name: fulfillment_order
      - name: ITEM_SUMMARY
      - name: LISTED_ITEM
      - name: LISTED_ITEM_ISSUE
      - name: LISTED_ITEM_OFFERS
      - name: LISTED_ITEM_SUMMARY 
      - name: ORDER_ITEM_PROMOTION_ID  

  - name: portable_gorgias
    database: raw
    schema: portable_gorgias
    tables:
      - name: customers
      - name: messages
      - name: tickets
      - name: custom_fields
      - name: views
      - name: view_items
      - name: jobs
      - name: users
      - name: macros
      - name: tags
      - name: satisfaction_surveys
      - name: ticket_details
      - name: ticket_tag

  - name: portable_shopify
    database: raw    
    schema: portable_shopify
    tables:
      - name: customers
      - name: discount_codes
      - name: inventory_levels
      - name: orders
      - name: products
  
  - name: portable_okendo
    database: raw    
    schema: portable_okendo
    tables:
      - name: reviews
  
  - name: portable_recharge
    database: raw    
    schema: portable_recharge
    tables:
      - name: customers
      - name: charges
      - name: orders
      - name: subscriptions

  - name: portable_klaviyo
    database: raw
    schema: portable_klaviyo
    tables:
      - name: accounts
      - name: campaigns
      - name: events
      - name: flows
      - name: flow_tags
      - name: forms
      - name: form_versions
      - name: lists
      - name: list_tags
      - name: metrics
      - name: metric_flow_triggers
      - name: profiles
      - name: segments
      - name: segment_flow_triggers
      - name: tags
      - name: tag_groups
      - name: templates
 
  - name: PORTABLE_NORTHBEAM
    database: raw
    schema: PORTABLE_NORTHBEAM
    tables:
      - name: data_export_results

  - name: FIVETRAN_ATTENTIVE
    database: raw
    schema: FIVETRAN_ATTENTIVE
    tables:
      - name: sms_sent      
